# Generated by Django 5.0.14 on 2026-06-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisti',
            new_name='PageVisit',
        ),
    ]
